config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challengu</title>
    <%= csrf_meta_tags %>
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        CHALLENGU
                    </a>
                </li>
                <li>
                  <%= link_to "Home", root_path %>
                </li>
                <li>
                  <%= link_to "About", about_path %>
                </li>
                <li>
                  <%= link_to "Contact", contact_path %>
                </li>
                <% if user_signed_in? %>
                <li>
                  <%= link_to "Logout", signout_path, method: :delete %>
                </li>
                <% else %>
                <li>
                  <%= link_to "Sign up", signup_path %>
                </li>
                <li class="sidebar-signin">
                  <%= link_to "Sign in", signin_path %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <% flash.each do |name, message| %>
                  <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
                <% end %>
                <%= yield %>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
  </body>
  <footer>
    <!-- jQuery -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
  </footer>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About Us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com" rel="nofollow">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact Us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com" rel="nofollow">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to Challengu</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>
<% else %>
<div class="row">
    <div class="home-wrap">
      <h1>FIFA Tournament<br> Management<br> Made Easy</h1>
      <span class="sub-home">Create, Manage and Join Fifa Tournaments</span>
      <a href="#" class="btn btn-primary btn-lg">Join Now</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>


<% end %>

app/views/pages/login.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Log In Here</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com" rel="nofollow">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/sign-up.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Sign up Here</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com" rel="nofollow">One Month Rails</a>.</p>
    </div>
</div>